version: '3'
networks:
  laravel: null
services:
  admincars:
    image: 'nginx:stable-alpine'
    container_name: webserver
    ports:
      - '8088:80'
    volumes:
      - './admincars/:/var/www'
      - './admincars/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mongo
    networks:
      - laravel
    mongo:
      image: mongo
      restart: always
      ports:
        - '27017:27017'
      networks:
        - laravel
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    php:
      build:
        context: ./admincars
        dockerfile: ./admincars/Dockerfile
      container_name: phplumen
      volumes:
        - './admincars/:/var/www'
      ports:
        - '9000:9000'
      networks:
        - laravel
  adminaccounts:
    image: 'nginx:stable-alpine'
    container_name: webserver2
    ports:
      - '8089:80'
    volumes:
      - './adminaccounts/:/var/www'
      - './adminaccounts/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
    networks:
      - laravel
    php:
      build:
        context: ./adminaccounts
        dockerfile: ./adminaccounts/Dockerfile
      container_name: phplumen2
      volumes:
        - './adminaccounts/:/var/www'
      ports:
        - '9001:9000'
      networks:
        - laravel
  login:
    image: 'nginx:stable-alpine'
    container_name: webserver1
    ports:
      - '8087:80'
    volumes:
      - './login/:/var/www'
      - './login/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    mysql:
      image: 'mysql:5.7.22'
      container_name: databasedev
      restart: unless-stopped
      tty: true
      ports:
        - '3306:3306'
      volumes:
        - './login/mysql:/var/lib/mysql'
      environment:
        MYSQL_DATABASE: access
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_PASSWORD: test122
        MYSQL_USER: developer
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      networks:
        - laravel
    php:
      build:
        context: ./login
        dockerfile: ./login/Dockerfile
      container_name: phplumen
      volumes:
        - './login/:/var/www'
      ports:
        - '9002:9000'
      networks:
        - laravel
