version: '3'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver2
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
#      - admincars_mongo_1
    networks:
      - laravel
#  mongo:
#    image: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    networks:
#      - laravel
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phplumen2
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    networks:
      - laravel
