version: '3'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mongo
    networks:
      - laravel
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - laravel
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phplumen
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
